// top bit set means command acknowledge
// replies contain error codes
// <0> command acknowledge, <1> error code, <2> data

module.exports = Object.freeze({

    CONNECT: 1,
    DISCONNECT: 2,
    DISCONNECT_CLIENT: 3,
    PUBLISH: 5,
    UNPUBLISH: 6,
    SUBSCRIBE: 9,
    SUBSCRIBE_ALL: 10,
    UNSUBSCRIBE: 11,
    UNSUBSCRIBE_ALL: 12,
    GET_HAT_TYPE_VERSION: 32,
    LIST_CLIENTS: 35,
    LIST_TOPICS: 38,
    READ_TOPIC: 40,
    WRITE_TOPIC: 42,


    UNKNOWN_ERROR: 236,
    BUFFER_TOO_SMALL: 237,
    INVALID_COMMAND: 238,
    INVALID_COMMAND_LENGTH: 239,
    ALREADY_SUBSCRIBED: 240,
    ASYNC_QUEUE_FULL: 241,
    TOPIC_SEND_FAILED: 242,
    INVALID_CLIENT_ID: 243,
    INVALID_TOPIC_ID: 244,
    TOPIC_HAS_SUBSCRIBERS: 245,
    CLIENT_NOT_FOUND: 246,
    TOPIC_NOT_FOUND: 247,
    SUBSCRIPTION_NOT_FOUND: 248,
    NO_TOPIC_SPACE: 249,
    NO_CLIENT_SPACE: 250,
    NO_SUBSCRIPTION_SPACE: 251,
    TOPIC_SAVE_FAILED: 252,
    TOPIC_DATA_SAVE_FAILED: 253,
    CLIENT_SAVE_FAILED: 254,
    CLIENT_SUBSCRIPTION_SAVE_FAILED: 255,
    OK: 1,
})
