// top bit set means command acknowledge
// replies contain error codes
// <0> command acknowledge, <1> error code, <2> data

module.exports = Object.freeze({

    CONNECT: 1,
    DISCONNECT: 2,
    DISCONNECT_CLIENT: 3,
    PUBLISH: 5,
    UNPUBLISH: 6,
    SUBSCRIBE: 9,
    SUBSCRIBE_ALL: 10,
    UNSUBSCRIBE: 11,
    UNSUBSCRIBE_ALL: 12,
    GET_HAT_TYPE_VERSION: 32,
    LIST_CLIENTS: 35,
    LIST_TOPICS: 38,
    READ_TOPIC: 40,
    WRITE_TOPIC: 42,


    OK: 0,
    UNKNOWN_ERROR: 1,
    INVALID_LENGTH: 2,
    BUFFER_TOO_SMALL: 3,
    INVALID_COMMAND: 4,
    INVALID_COMMAND_LENGTH: 5,
    ALREADY_SUBSCRIBED: 6,
    ASYNC_QUEUE_FULL: 7,
    MESSAGE_SEND_FAILED: 8,
    INVALID_CLIENT_ID: 9,
    INVALID_TOPIC: 10,
    TOPIC_HAS_SUBSCRIBERS: 11,
    CLIENT_NOT_FOUND: 12,
    TOPIC_NOT_FOUND: 13,
    SUBSCRIPTION_NOT_FOUND: 14,
    NO_MESSAGE_SPACE: 15,
    NO_CLIENT_SPACE: 16,
    NO_SUBSCRIPTION_SPACE: 17,
    MESSAGE_SAVE_FAILED: 18,
    MESSAGE_DATA_SAVE_FAILED: 19,
    CLIENT_SAVE_FAILED: 20,
    CLIENT_SUBSCRIPTION_SAVE_FAILED: 21,
})
