// top bit set means command acknowledge
// replies contain error codes
// <0> command acknowledge, <1> error code, <2> data

module.exports = Object.freeze({


    CONNECT: 1,
    CONNECT_ACKNOWLEDGE: 129,

    DISCONNECT: 2,
    DISCONNECT_ACKNOWLEDGE: 130,

    IS_CLIENT: 3,
    IS_CLIENT_ACKNOWLEDGE: 131,

    CREATE: 4,
    CREATE_ACKNOWLEDGE: 132,

    UPDATE: 5,
    UPDATE_ACKNOWLEDGE: 133,

    READ: 6,
    READ_ACKNOWLEDGE: 134,

    SUBSCRIBE: 7,
    SUBSCRIBE_ACKNOWLEDGE: 135,

    UNSUBSCRIBE: 8,
    UNSUBSCRIBE_ACKNOWLEDGE: 136,

    LIST_CLIENTS: 9,
    LIST_CLIENTS_ACKNOWLEDGE: 137,

    GET_TYPE_VERSION: 10,
    GET_TYPE_VERSION_ACKNOWLEDGE: 138,


    UNKNOWN_ERROR: -13,
    INVALID_CLIENT_ID: -12,
    INVALID_TOPIC_ID: -11,
    TOPIC_HAS_SUBSCRIBERS: -10,
    CLIENT_NOT_FOUND: -9,
    TOPIC_NOT_FOUND: -8,
    SUBSCRIPTION_NOT_FOUND: -7,
    NO_TOPIC_SPACE: -6,
    NO_CLIENT_SPACE: -5,
    NO_SUBSCRIPTION_SPACE: -4,
    TOPIC_SAVE_FAILED: -3,
    TOPIC_DATA_SAVE_FAILED: -2,
    CLIENT_SAVE_FAILED: -1,
    CLIENT_SUBSCRIPTION_SAVE_FAILED: 0,
    OK: 1,
})
