module.exports = Object.freeze({
    COMMAND_INVALID: 1,
    DATA_INVALID: 2,
    ADDRESS_INVALID: 3,
    HAT_NOT_FOUND: 50,
    OPEN_PORT_TIMEOUT: 100,
    CLOSE_PORT_TIMEOUT: 101,
    RECEIVE_TIMEOUT: 102
})
